# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
        ('courseApp', '0002_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_creator',
            field=models.ManyToManyField(to='loginApp.User'),
        ),
    ]
